### ISSUE TITLE
Remove asynctest

### ISSUE THREAD

**Issue by fabaff** [jeeftor/intellifire4py#9]
asynctest is no longer supported and doesn't work with Python 3.11 (Martiusweb/asynctest#163).

**Comment by jeeftor** [comment]
Do you happen to know what the replacement is?

**Comment by mweinelt** [comment]
> Do you happen to know what the replacement is?

https://github.com/Martiusweb/asynctest/issues/163#issuecomment-1356329963

**Comment by jeeftor** [comment]
Starting to actually look at this again

**Comment by jeeftor** [comment]
I think its gone now
